Rubik's cube simulator: Rubik::Orientation Class Reference
Rubik::Orientation Class Reference
#include <side.hh>
Public Member Functions
Orientation & top (int t)
Orientation & bottom (int b)
Orientation & left (int l)
Orientation & right (int r)
int top () const
int bottom () const
int left () const
int right () const
std::array< int, 9 > transformation (int top) const
Private Attributes
boost::optional< int > top_
boost::optional< int > bottom_
boost::optional< int > left_
boost::optional< int > right_
Friends
std::ostream & operator<< (std::ostream &os, Rubik::Orientation const &o)
Detailed Description
Definition at line 10 of file side.hh.
Member Function Documentation
Orientation & Rubik::Orientation::bottom (int b)
Definition at line 59 of file side.cc.
References bottom_.
   {
     bottom_ = b;
     return *this;
   }
int Rubik::Orientation::bottom () const
Definition at line 82 of file side.cc.
References bottom_.
   {
     return *bottom_;
   }
Orientation & Rubik::Orientation::left (int l)
Definition at line 65 of file side.cc.
References left_.
   {
     left_ = l;
     return *this;
   }
int Rubik::Orientation::left () const
Definition at line 87 of file side.cc.
References left_.
   {
     return *left_;
   }
Orientation & Rubik::Orientation::right (int r)
Definition at line 71 of file side.cc.
References right_.
   {
     right_ = r;
     return *this;
   }
int Rubik::Orientation::right () const
Definition at line 92 of file side.cc.
References right_.
   {
     return *right_;
   }
Orientation & Rubik::Orientation::top (int t)
Definition at line 53 of file side.cc.
References top_.
   {
     top_ = t;
     return *this;
   }
int Rubik::Orientation::top () const
Definition at line 77 of file side.cc.
References top_.
   {
     return *top_;
   }
std::array< int, 9 > Rubik::Orientation::transformation (int top) const
Definition at line 97 of file side.cc.
References bottom(), anonymous_namespace{side.cc}::Identity, left(), right(), anonymous_namespace{side.cc}::RotateHalf, anonymous_namespace{side.cc}::RotateLeft, anonymous_namespace{side.cc}::RotateRight, and top().
   {
     std::map<int, std::array<int, 9> const> const transformations = boost::assign::map_list_of
       (this->top(), Identity)
       (this->left(), RotateRight)
       (this->bottom(), RotateHalf)
       (this->right(), RotateLeft);
     return transformations.at(top);
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, Rubik::Orientation const & o) friend
Definition at line 169 of file side.cc.
   {
     os << '('
        << "Top: " << o.top_ << ", "
        << "Left: " << o.left_ << ", "
        << "Bottom: " << o.bottom_ << ", "
        << "Right: " << o.right_
        << ')';
     return os;
   }
Member Data Documentation
boost::optional<int> Rubik::Orientation::bottom_ private
Definition at line 14 of file side.hh.
boost::optional<int> Rubik::Orientation::left_ private
Definition at line 15 of file side.hh.
boost::optional<int> Rubik::Orientation::right_ private
Definition at line 16 of file side.hh.
boost::optional<int> Rubik::Orientation::top_ private
Definition at line 13 of file side.hh.
The documentation for this class was generated from the following files:
inc/side.hh
src/side.cc