Rubik's cube simulator: Rubik::Side Class Reference
Rubik::Side Class Reference
Represents one side of a cube.
#include <side.hh>
Public Types
typedef boost::shared_ptr< Side > Ptr
typedef std::array< int, 9 > Data
typedef std::array< int, 3 > Row
Public Member Functions
Side (Data const &data, Orientation const &orientation)
Data data ()
Data data (int top)
Retrieve side data from different perspectives.
Row topRow (int top)
Retrieve the top row, from different perspectives.
Static Public Member Functions
static Ptr create (Data const &data, Orientation const &orientation)
Private Attributes
Data data_
Orientation orientation_
Detailed Description
Represents one side of a cube.
Since a side of a cube has no natural orientation (top, bottom, left and right pretty soon become meaningless), a side is orented relative to the color of the center square of their adjacent sides.
Definition at line 47 of file side.hh.
Member Typedef Documentation
typedef std::array<int,9> Rubik::Side::Data
Definition at line 51 of file side.hh.
typedef boost::shared_ptr<Side> Rubik::Side::Ptr
Definition at line 50 of file side.hh.
typedef std::array<int,3> Rubik::Side::Row
Definition at line 52 of file side.hh.
Constructor & Destructor Documentation
Rubik::Side::Side (Side::Data const & data, Orientation const & orientation)
Definition at line 137 of file side.cc.
     : data_(data), orientation_(orientation)
   {}
Member Function Documentation
Side::Ptr Rubik::Side::create (Side::Data const & data, Orientation const & orientation) static
Definition at line 132 of file side.cc.
References Side().
   {
     return Ptr(new Side(data, orientation));
   }
Side::Data Rubik::Side::data ()
Definition at line 141 of file side.cc.
References data_.
   {
     return data_;
   }
Side::Data Rubik::Side::data (int top)
Retrieve side data from different perspectives.
Side is oriented relative to the center squares of its neighbouring sides. This function allows you to "rotate the cube" by specifying what is the color of the center square of the top neighbouring side. This function will then return the colors of the squares properly adjusted for this new orientation.
Definition at line 146 of file side.cc.
References data_, orientation_, anonymous_namespace{side.cc}::transform(), and Rubik::Orientation::transformation().
   {
     return transform(orientation_.transformation(top), data_);
   }
Side::Row Rubik::Side::topRow (int top)
Retrieve the top row, from different perspectives.
Similar to the data(int) function, this returns the top row, adjacent to the center square color specified.
Definition at line 151 of file side.cc.
References data(), anonymous_namespace{side.cc}::TopRow, and anonymous_namespace{side.cc}::transform().
   {
     return transform(TopRow, data(top));
   }
Member Data Documentation
Data Rubik::Side::data_ private
Definition at line 55 of file side.hh.
Orientation Rubik::Side::orientation_ private
Definition at line 56 of file side.hh.
The documentation for this class was generated from the following files:
inc/side.hh
src/side.cc