Rubik's cube simulator: Rubik::FixedCube Class Reference
Rubik::FixedCube Class Reference
A cube that cannot be rotated.
#include <fixedcube.hh>
Public Types
typedef boost::shared_ptr
< FixedCube > Ptr
typedef boost::function
< ISide::Ptr(Side::Data const
&, Orientation const &)> SideFactory
Public Member Functions
CubeData data ()
Static Public Member Functions
static Ptr create (CubeData const &data)
static Ptr create (CubeData const &data, SideFactory const &sideFactory)
Private Member Functions
FixedCube (CubeData const &data, SideFactory const &sideFactory)
Private Attributes
CubeData data_
Detailed Description
A cube that cannot be rotated.
This cube never changes orientation. I.e. the center squares of each of the six sides always stay in the same place. The only operations that are supported is rotating each of the six sides a quarter turn clockwise.
Definition at line 58 of file fixedcube.hh.
Member Typedef Documentation
typedef boost::shared_ptr<FixedCube> Rubik::FixedCube::Ptr
Definition at line 61 of file fixedcube.hh.
typedef boost::function<ISide::Ptr(Side::Data const&, Orientation const&)> Rubik::FixedCube::SideFactory
Definition at line 62 of file fixedcube.hh.
Constructor & Destructor Documentation
Rubik::FixedCube::FixedCube (CubeData const & data, SideFactory const & sideFactory) private
Definition at line 217 of file fixedcube.cc.
References Rubik::CubeData::top().
     : data_(data)
   {
     for(int i=0; i<6; i++)
       sideFactory(data.top(), Orientation());
   }
Member Function Documentation
FixedCube::Ptr Rubik::FixedCube::create (CubeData const & data) static
Definition at line 224 of file fixedcube.cc.
References Rubik::Side::create(), and FixedCube().
   {
     return Ptr(new FixedCube(data, Side::create));
   }
FixedCube::Ptr Rubik::FixedCube::create (CubeData const & data, SideFactory const & sideFactory) static
Definition at line 229 of file fixedcube.cc.
References FixedCube().
   {
     return Ptr(new FixedCube(data, sideFactory));
   }
CubeData Rubik::FixedCube::data ()
Definition at line 234 of file fixedcube.cc.
References data_.
   {
     return data_;
   }
Member Data Documentation
CubeData Rubik::FixedCube::data_ private
Definition at line 64 of file fixedcube.hh.
The documentation for this class was generated from the following files:
inc/fixedcube.hh
src/fixedcube.cc