Rubik's cube simulator: Rubik::anonymous_namespace{fixedcube.cc} Namespace Reference
Rubik::anonymous_namespace{fixedcube.cc} Namespace Reference
Functions
void updateMax (int &max, boost::optional< Side::Data > data)
int numDigits (int i)
std::string row (int i, const int digits, boost::optional< Side::Data > const &data)
void dumpInTheMiddle (std::ostream &os, const int digits, std::string const &name, boost::optional< Side::Data > const &data)
void dumpSideBySide (std::ostream &os, const int digits, std::string const &nameOne, boost::optional< Side::Data > const &dataOne, std::string const &nameTwo, boost::optional< Side::Data > const &dataTwo, std::string const &nameThree, boost::optional< Side::Data > const &dataThree)
Function Documentation
void Rubik::anonymous_namespace{fixedcube.cc}::dumpInTheMiddle (std::ostream & os, const int digits, std::string const & name, boost::optional< Side::Data > const & data)
Definition at line 56 of file fixedcube.cc.
References row().
     {
       const int rowWidth = 2+3*digits;
       const std::string emptyRow(rowWidth+3, ' ');
       os << emptyRow << name << std::endl;
       for(int i=0; i<3; i++)
         os << emptyRow << row(i, digits, data) << std::endl;
       os << std::endl;
     }
void Rubik::anonymous_namespace{fixedcube.cc}::dumpSideBySide (std::ostream & os, const int digits, std::string const & nameOne, boost::optional< Side::Data > const & dataOne, std::string const & nameTwo, boost::optional< Side::Data > const & dataTwo, std::string const & nameThree, boost::optional< Side::Data > const & dataThree)
Definition at line 68 of file fixedcube.cc.
References Rubik::left(), and row().
     {
       int rowWidth = 2+3*digits;
       os << std::setw(rowWidth) << std::left << nameOne << "   "
          << std::setw(rowWidth) << std::left << nameTwo << "   "
          << std::setw(rowWidth) << std::left << nameThree << std::endl;
       for(int i=0; i<3; i++)
         os << row(i, digits, dataOne) << "   "
            << row(i, digits, dataTwo) << "   "
            << row(i, digits, dataThree) << std::endl;
       os << std::endl;
     }
int Rubik::anonymous_namespace{fixedcube.cc}::numDigits (int i)
Definition at line 18 of file fixedcube.cc.
     {
       int digits = 0;
       if(i)
       {
         while (i)
         {
           i /= 10;
           digits++;
         }
       }
       else
         digits = 1;
       return digits;
     }
std::string Rubik::anonymous_namespace{fixedcube.cc}::row (int i, const int digits, boost::optional< Side::Data > const & data)
Definition at line 35 of file fixedcube.cc.
     {
       std::stringstream s;
       if(data)
       {
         Side::Data::const_iterator iter = data->begin()+3*i;
         s << std::setw(digits) << *iter++ << ' ';
         s << std::setw(digits) << *iter++ << ' ';
         s << std::setw(digits) << *iter++;
       }
       else
       {
         s << std::setw(digits) << '.' << ' ';
         s << std::setw(digits) << '.' << ' ';
         s << std::setw(digits) << '.';
       }
       return s.str();
     }
void Rubik::anonymous_namespace{fixedcube.cc}::updateMax (int & max, boost::optional< Side::Data > data)
Definition at line 10 of file fixedcube.cc.
     {
       if(data)
       {
         max = std::max(max, *std::max_element(data->begin(), data->end()));
       }
     }