Rubik's cube simulator: Rubik Namespace Reference
Rubik Namespace Reference
Classes
class CubeData
class FixedCube
A cube that cannot be rotated.
class Orientation
class Side
Represents one side of a cube.
Functions
CubeData top (Side::Data const &data)
CubeData bottom (Side::Data const &data)
CubeData left (Side::Data const &data)
CubeData right (Side::Data const &data)
CubeData front (Side::Data const &data)
CubeData back (Side::Data const &data)
Orientation top (int t)
Orientation bottom (int b)
Orientation left (int l)
Orientation right (int r)
std::ostream & operator<< (std::ostream &os, Side::Data const &data)
std::ostream & operator<< (std::ostream &os, Orientation const &o)
Function Documentation
CubeData Rubik::back (Side::Data const & data)
Definition at line 35 of file fixedcube.cc.
References Rubik::CubeData::back().
   {
     CubeData c;
     return c.back(data);
   }
CubeData Rubik::bottom (Side::Data const & data)
Definition at line 11 of file fixedcube.cc.
References Rubik::CubeData::bottom().
   {
     CubeData c;
     return c.bottom(data);
   }
Orientation Rubik::bottom (int b)
Definition at line 114 of file side.cc.
References Rubik::Orientation::bottom().
   {
     Orientation o;
     return o.bottom(b);
   }
CubeData Rubik::front (Side::Data const & data)
Definition at line 29 of file fixedcube.cc.
References Rubik::CubeData::front().
   {
     CubeData c;
     return c.front(data);
   }
CubeData Rubik::left (Side::Data const & data)
Definition at line 17 of file fixedcube.cc.
References Rubik::CubeData::left().
   {
     CubeData c;
     return c.left(data);
   }
Orientation Rubik::left (int l)
Definition at line 120 of file side.cc.
References Rubik::Orientation::left().
   {
     Orientation o;
     return o.left(l);
   }
std::ostream & Rubik::operator<< (std::ostream & os, Side::Data const & data)
Definition at line 156 of file side.cc.
   {
     os << std::endl
        << '[' << data[0] << ' ' << data[1] << ' ' << data[2] << ']' << std::endl
        << '[' << data[3] << ' ' << data[4] << ' ' << data[5] << ']' << std::endl
        << '[' << data[6] << ' ' << data[7] << ' ' << data[8] << ']' << std::endl;
     return os;
   }
std::ostream & Rubik::operator<< (std::ostream & os, Rubik::Orientation const & o)
Definition at line 166 of file side.cc.
References Rubik::Orientation::bottom_, Rubik::Orientation::left_, Rubik::Orientation::right_, and Rubik::Orientation::top_.
   {
     os << '('
        << "Top: " << o.top_ << ", "
        << "Left: " << o.left_ << ", "
        << "Bottom: " << o.bottom_ << ", "
        << "Right: " << o.right_
        << ')';
     return os;
   }
CubeData Rubik::right (Side::Data const & data)
Definition at line 23 of file fixedcube.cc.
References Rubik::CubeData::right().
   {
     CubeData c;
     return c.right(data);
   }
Orientation Rubik::right (int r)
Definition at line 126 of file side.cc.
References Rubik::Orientation::right().
   {
     Orientation o;
     return o.right(r);
   }
CubeData Rubik::top (Side::Data const & data)
Definition at line 5 of file fixedcube.cc.
References Rubik::CubeData::top().
   {
     CubeData c;
     return c.top(data);
   }
Orientation Rubik::top (int t)
Definition at line 108 of file side.cc.
References Rubik::Orientation::top().
   {
     Orientation o;
     return o.top(t);
   }