#!/bin/bash

# set -x
set -e
set -u

if ! [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_JOB_NUMBER}" = "${TRAVIS_BUILD_NUMBER}.1" ]
then
    # Doxygen not generated
    exit 0
fi

# Log
cat doxygen.log

# Settings
REPO_PATH=git@github.com:kees-jan/rubik.git
HTML_PATH=$(pwd)/html
COMMIT_USER="Documentation Builder"
COMMIT_EMAIL="project@mandryn.org"
CHANGESET=$(git rev-parse --verify HEAD)

GH_DIR=$(mktemp -d)

# Get a clean version of the HTML documentation repo.
git clone -b gh-pages "${REPO_PATH}" --single-branch ${GH_DIR}

# rm all the files through git to prevent stale files.
pushd ${GH_DIR}
git rm -rf .
cp -r ${HTML_PATH}/* .
git add .

# Commit and push
git config user.name "${COMMIT_USER}"
git config user.email "${COMMIT_EMAIL}"
git commit -m "Automated documentation build for branch ${TRAVIS_BRANCH}, changeset ${CHANGESET}."
git push origin gh-pages

# Cleanup
popd
rm -rf ${GH_DIR}
